package com.x.miaosha.dao;

import com.x.miaosha.dataobject.GoodsDO;

import java.util.ArrayList;

public interface GoodsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int insert(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int insertSelective(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    GoodsDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int updateByPrimaryKey(GoodsDO record);

    ArrayList<GoodsDO> selectList();
}