package com.x.miaosha.dao;

import com.x.miaosha.dataobject.StockDO;

public interface StockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int insert(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int insertSelective(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    StockDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int updateByPrimaryKeySelective(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    int updateByPrimaryKey(StockDO record);

    StockDO selectByGoodsId(Integer GoodsId);
}