package com.x.miaosha.dataobject;

public class StockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.goods_id
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.goods_id
     *
     * @return the value of stock.goods_id
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.goods_id
     *
     * @param goodsId the value for stock.goods_id
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock
     *
     * @return the value of stock.stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock
     *
     * @param stock the value for stock.stock
     *
     * @mbg.generated Sat Apr 13 11:08:00 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}